### ISSUE TITLE
Cocoapods: Could not locate login item

### ISSUE THREAD

**Issue by brene** [sindresorhus/LaunchAtLogin#21] opened 2018-12-24 09:22 UTC
# Edited with new information:
When you install the cocoapod, this module doesn't actually work. But it works when you use Carthage.

# Original bug:
First off, thanks for kicking off a project like this. It looks really helpful and seems super easy to use. But when I integrate it. And try to toggle the `LaunchAtLogin.isEnabled`, it just shows me this as an error.
```
2018-12-24 01:19:21.312633-0800 YoctoChat[7479:335659] Could not locate login item renebrandel.YoctoChat-LaunchAtLoginHelper in the caller's bundle
2018-12-24 01:19:21.313307-0800 YoctoChat[7479:335659] Could not enable login item: renebrandel.YoctoChat-LaunchAtLoginHelper: 3: No such process
2018-12-24 01:19:21.325436-0800 YoctoChat[7479:335659] Could not enable login item: renebrandel.YoctoChat-LaunchAtLoginHelper: 3: No such process
```
-Rene
I've enabled codesigning and tried other solution of resolved issues but no luck so far. Any idea on how to debug this?

**Comment by sindresorhus** [comment] 2018-12-27 17:39
See https://github.com/sindresorhus/LaunchAtLogin/issues/11 for some debugging help and examples.

**Comment by wes566** [comment] 2019-02-01 16:20
@brene are you using Carthage or Cocoapods to consume LaunchAtLogin?

**Comment by wes566** [comment] 2019-02-03 02:54
Switch to Carthage to get it working... the cocoapod is not working. I spent some time digging into the generated cocoapod config and the LaunchAtLoginHelper.app target is never built with cocoapods. That's why you get that error message.

**Comment by brene** [comment] 2019-04-01 16:38
@wes566 I tried using the Carthage, and it finally worked! Thanks so much for the help. I'm going to rename the bug to accurately represent the issue.

**Comment by sindresorhus** [comment] 2019-09-20 07:01
Duplicate of #22

**Closed by sindresorhus** 2019-09-20 07:01 UTC
