### ISSUE TITLE
Cannot find 'SMLoginItemSetEnabled' in scope

### ISSUE THREAD

**Issue by tommycarpi** [sindresorhus/LaunchAtLogin#78] opened 2022-07-10 09:43 UTC
Hello,

I was trying to integrate this functionality to a Catalyst app.
I added the package from Swift Package Manager, but after that the app does not compile with this error 😅
Did I miss something?

`Cannot find 'SMLoginItemSetEnabled' in scope`

<img width="1056" alt="Screenshot 2022-07-10 at 11 40 50" src="https://user-images.githubusercontent.com/10156527/178139475-56d980db-9277-4756-b777-565e57e3d39d.png">

**Comment by sindresorhus** [comment] 2022-07-10 21:32
Duplicate of #46

**Closed by sindresorhus** 2022-07-10 21:32 UTC
