### ISSUE TITLE
Cannot find 'SMAppService' in scope

### ISSUE THREAD

**Issue by kotercy9527** [sindresorhus/LaunchAtLogin#92] opened 2023-05-24 09:21 UTC
hello,
i face a question when use LaunchAtLogin
i added package in xcode first ,
then a add a run script
i build my target ,show me error."Cannot find 'SMAppService' in scope"

![1211684919806_ pic](https://github.com/sindresorhus/LaunchAtLogin/assets/31883359/460ae0cc-8d76-4486-ad5d-5e7feb11f39d)
![1221684919834_ pic](https://github.com/sindresorhus/LaunchAtLogin/assets/31883359/673eefe2-5d46-4342-86ac-430af7911912)

![1231684919878_ pic](https://github.com/sindresorhus/LaunchAtLogin/assets/31883359/2cd506fe-6f60-4347-b461-8d9a3e467230)
![1241684919929_ pic](https://github.com/sindresorhus/LaunchAtLogin/assets/31883359/e0f111dd-3a77-4d1b-808a-c77663a8d00a)

**Comment by sindresorhus** [comment] 2023-05-24 09:23
Duplicate of #87

**Closed by sindresorhus** 2023-05-24 09:23 UTC

**Comment by kotercy9527** [comment] 2023-05-24 09:24
thanks
